name: painter_pro
description: "Paint Estimator - Professional painting project management app."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  firebase_core: ^3.14.0
  firebase_crashlytics: ^4.3.7
  # TODO: Retirar o comentario aqui
  # firebase_app_distribution: ^1.1.1
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.7.0
  roomplan_flutter: ^0.0.8
  app_links: ^3.5.0
  logger: ^2.6.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path: ^1.9.0
  file_picker: ^10.3.2
  validatorless: ^1.2.4
  connectivity_plus: ^6.1.5
  image: ^4.1.7
  image_picker: ^1.0.7
  path_provider: ^2.1.4
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/camera/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
